Repository Enegrecer/enegrecer-web, pull requests merged in 2018-08, with the labels that each got.

#279 Adicionando no README os pré requisitos para executar e desenvolver o projeto
  README.md
Labels: necessita revisão

#280 Adicionado no README principal uma seção com as informações para configurar o ambiente
  README.md
  src/components/denuncias/SecaoForm.js
  src/components/denuncias/denuncia.css
  src/components/moderador/DenunciaRow.js
  src/components/sobre/__snapshots__/Sobre.test.js.snap
  src/components/sobre/colaboradores.js
  src/containers/denuncias/NovaDenunciaContainer.js
  src/routes/Routes.js
  src/routes/__snapshots__/Routes.test.js.snap
Labels: necessita revisão

#278 Adiciona Inessa Luerce às colaboradoras
  src/components/sobre/__snapshots__/Sobre.test.js.snap
  src/components/sobre/colaboradores.js
Labels: em andamento

#289 Waffle 285 - Adicionar estrutura para execução dos testes funcionais automatizados
  .eslintignore
  README.md
  functional-tests.conf.js
  package.json
  src/tests/functional/features/denuncia.feature
  src/tests/functional/pages/denuncia.js
  src/tests/functional/specs/denuncia.js
  yarn.lock
Labels: necessita revisão

#283 Adicionar o pre-commit hook para executar o ESLint antes dos commits
  package.json
  src/components/comum/gradeCampos/GradeCampos.js
  src/components/visualizarDenuncia/VisualizarDenuncia.js
  yarn.lock
Labels: necessita revisão

#288 Correção na exibição da lista de denúncias quando o registro não possui um agressor
  src/sagas/denuncia/listar.js
Labels: bug, necessita revisão

#291 Adicionar o pre-commit hook para executar o ESLint antes dos commits
  .eslintignore
  README.md
  functional-tests.conf.js
  package.json
  src/components/comum/gradeCampos/GradeCampos.js
  src/components/sobre/__snapshots__/Sobre.test.js.snap
  src/components/sobre/colaboradores.js
  src/components/visualizarDenuncia/VisualizarDenuncia.js
  src/sagas/denuncia/listar.js
  src/tests/functional/features/denuncia.feature
  src/tests/functional/pages/denuncia.js
  src/tests/functional/specs/denuncia.js
  yarn.lock
Labels: necessita revisão

#294 Remover diretório e teste funcional com estrutura duplicada
  .eslintignore
  src/components/comum/campoTexto/index.js
  src/testeFuncional/pages/denuncia.js
  src/testeFuncional/pages/home.js
  src/testeFuncional/pages/login.js
  src/testeFuncional/steps/steps_file.js
  src/testeFuncional/testes/jornadaDeUsuario_test.js
  yarn.lock
Labels: necessita revisão

#296 Sincroniza development com master
  .eslintignore
  src/components/comum/campoTexto/index.js
  src/components/comum/combobox/__snapshots__/Combobox.test.js.snap
  src/components/comum/combobox/index.js
  src/components/comum/comboboxEstado/__snapshots__/ComboboxEstado.test.js.snap
  src/components/comum/comboboxEstado/index.js
  src/components/comum/comboboxRaca/__snapshots__/ComboboxRaca.test.js.snap
  src/components/comum/comboboxRaca/index.js
  src/components/comum/genero/__snapshots__/Genero.test.js.snap
  src/components/comum/genero/index.js
  src/components/comum/nome/__snapshots__/Nome.test.js.snap
  src/components/comum/nome/index.js
  src/components/comum/validacoes/Validacoes.test.js
  src/components/comum/validacoes/index.js
  src/components/denuncias/NovaDenunciaForm.js
  src/components/denuncias/agressor/AgressorForm.js
  src/components/denuncias/agressor/__snapshots__/AgressorForm.test.js.snap
  src/components/denuncias/denunciante/DenuncianteForm.js
  src/components/denuncias/denunciante/__snapshots__/DenuncianteForm.test.js.snap
  src/components/denuncias/descricao/FormDescricao.js
  src/components/denuncias/descricao/__snapshots__/FormDescricao.test.js.snap
  src/components/denuncias/informacoesLegais/FormInformacoesLegais.js
  src/components/denuncias/informacoesLegais/__snapshots__/FormInformacoesLegais.test.js.snap
  src/components/moderador/DenunciaRow.js
  src/components/moderador/painel-moderador.css
  src/components/moderador/painelModerador.js
  src/components/sobre/__snapshots__/Sobre.test.js.snap
  src/components/sobre/colaboradores.js
  src/containers/denuncias/NovaDenunciaContainer.js
  src/testeFuncional/pages/denuncia.js
  src/testeFuncional/pages/home.js
  src/testeFuncional/pages/login.js
  src/testeFuncional/steps/steps_file.js
  src/testeFuncional/testes/jornadaDeUsuario_test.js
  yarn.lock
Labels: necessita revisão
